global:
  scrape_interval: 1s
scrape_configs:
 - job_name: simple-ping-app
   scheme: https
   tls_config:
    insecure_skip_verify: true
   static_configs:
    - targets:
       - simple-ping-container:1443
remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    basic_auth:
      username_file: ./username_grafana.key
      password_file: ./password_grafana.key

